name: Práctica final Github Actionte Moisés Guerola
on:
  push:
    branches: [ main ]
jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      
  cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypressTests
      - name: Guardar resultado en Result.txt
        run: echo ${{ steps.cypressTests.outcome }} > result.txt
      - name: Upload Artifact Result
        uses: actions/upload-artifact@v3
        with:
          name: test_result
          path: result.txt

  badge_job:
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Result from Artifact
        uses: actions/download-artifact@v3
        with:
          name: test_result
      - name: Get Result Value
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: result_cypress_tests
      - name: Update Readme
        uses: "./.github/actions/update_readme"
        with:
          result: ${{ steps.result_cypress_tests.outputs.cypress_outcome }}
      - name: Commit Readme Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: ${{ github.event.pusher.name }}
          author_email: ${{ github.event.pusher.email }}
          message: "Result of the tests on Cypress"
          push: true