name: Práctica final Github Actions Moisés Guerola
on:
  push:
    branches: [ main ]
jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      
  # cypress_job:
  #   runs-on: ubuntu-latest
  #   needs: [ linter_job ]
